import Vue from 'vue'
import { Button, NavBar, Tabbar, TabbarItem, Grid, GridItem, Card, Swipe, SwipeItem, Lazyload, Image, Stepper, Toast, Icon, List, PullRefresh, Cell, Notify, Field } from 'vant'

Vue.use(Button)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Image)
Vue.use(Stepper)
Vue.use(Toast)
Vue.use(Icon)
Vue.use(Card)
Vue.use(Image)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Cell)
Vue.use(Notify)
Vue.use(Field)